### ISSUE TITLE
Install fails on SSD drives

### ISSUE THREAD

**Issue by ghost** [solus-project/os-installer#33]
I installed Solus on a laptop with and SSD drive and a PC with Samsung Evo 950 SSD. In both cases I opted to remove all partitions and make a clean install and in both cases the installation failed saying that it could not write to drives.

After restarting, all the partitions were gone and if I exactly repeat the steps as before everything installs without a problem. In both cases Solus was overwriting Ubuntu partitions. 

Can't really test it again as I now installed Solus on both PCs but thought I would report it.

**Comment by ikeydoherty** [comment]
What did the existing partition layout look like? And what was the *actual* error?

**Comment by ghost** [comment]
Sorry for not specifying this, I presumed that it was a unrelated error (so did not though about taking a picture of the message) but then noticed the same pattern happened twice with both my PC and notebook.

The partition layout was the one that is automatically created when installing Ubuntu 16.04. The error mentioned that the installation failed and it could not write to the disk (this is as much as I remember). It did delete all the partitions but it was not able to copy anything (the progress bar did not even initiate). After a restart everything was copied without a problem.

Not sure if it matters but I was using UEFI boot process in both cases. Those were normal partitions, without any encryption or LVM.

**Comment by ikeydoherty** [comment]
Yeah it was actually the LVM thing I was curious about

**Comment by ghost** [comment]
Think this was solved with the new build and can be closed?

**Comment by FilBot3** [comment]
I'm still having issues with SSD's withe the same error as above with Solus-2017.04.18.0-Budgie

**Comment by ekskido** [comment]
I can confirm that the issue is still there

**Comment by midtoad** [comment]
I also was unable to install to the hard drive, but I was trying to create a virtual box hard drive on a Macintosh. I simply unchecked the option to create a boot loader, and then all was well.

By the way, the error message I saw was the following:

solus could not commit to disk py_ped_disk_commit
